language: haskell
sudo: false

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xv --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

addons:
  apt:
    packages:
      - libgmp-dev

install:
  - ./travis_long stack --no-terminal setup
  - ./travis_long stack --no-terminal test --only-snapshot

script:
  - stack --no-terminal test
